extends RefCounted
class_name ProofData

const PROOF_PATH := "user://exports/play_proof.txt"

static func load_proof() -> Dictionary:
	var data := {
		"player_id": "",
		"playthrough_count": 0,
		"total_days_played": 0
	}

	if not FileAccess.file_exists(PROOF_PATH):
		data["player_id"] = _generate_player_id()
		save_proof(data)
		return data

	var file := FileAccess.open(PROOF_PATH, FileAccess.READ)
	if file == null:
		data["player_id"] = _generate_player_id()
		return data

	while not file.eof_reached():
		var line := file.get_line().strip_edges()
		if line.is_empty():
			continue

		var parts := line.split("=", false, 2)
		if parts.size() != 2:
			continue

		var key := parts[0].strip_edges()
		var value := parts[1].strip_edges()

		match key:
			"player_id":
				data["player_id"] = value
			"playthrough_count":
				data["playthrough_count"] = int(value)
			"total_days_played":
				data["total_days_played"] = int(value)

	file.close()

	if data["player_id"] == "":
		data["player_id"] = _generate_player_id()
		save_proof(data)

	return data


static func save_proof(data: Dictionary) -> void:
	_ensure_export_folder()
	
	var file := FileAccess.open(PROOF_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Could not write proof file.")
		return

	file.store_line("Do not edit this file manually.")
	file.store_line("Generated by the game for questionnaire verification.")
	file.store_line("")
	file.store_line("player_id=%s" % str(data.get("player_id", "")))
	file.store_line("playthrough_count=%d" % int(data.get("playthrough_count", 0)))
	file.store_line("total_days_played=%d" % int(data.get("total_days_played", 0)))

	file.close()


static func sync_from_progress(progress: Dictionary) -> void:
	var proof := load_proof()
	proof["playthrough_count"] = int(progress.get("playthrough_count", 0))
	proof["total_days_played"] = int(progress.get("total_days_played", 0))
	save_proof(proof)


static func clear_all_data() -> void:
	var fresh_data := {
		"player_id": _generate_player_id(),
		"playthrough_count": 0,
		"total_days_played": 0
	}
	save_proof(fresh_data)


static func _generate_player_id() -> String:
	return "%s-%s-%s-%s" % [
		_hex_block(8),
		_hex_block(4),
		_hex_block(4),
		_hex_block(12)
	]


static func _hex_block(length: int) -> String:
	var chars := "0123456789abcdef"
	var result := ""

	for i in range(length):
		result += chars[randi() % chars.length()]

	return result

static func _ensure_export_folder():
	var dir := DirAccess.open("user://")
	if not dir.dir_exists("exports"):
		dir.make_dir("exports")
